
_interrupt:

;GPS.c,25 :: 		void interrupt() {
;GPS.c,26 :: 		if (RCIF_bit == 1) {             // If interrupt is generated by RCIF
	BTFSS       RCIF_bit+0, BitPos(RCIF_bit+0) 
	GOTO        L_interrupt0
;GPS.c,27 :: 		txt[i] = UART_Read();         // Read data and store it to txrt string
	MOVLW       _txt+0
	ADDWF       _i+0, 0 
	MOVWF       FLOC__interrupt+0 
	MOVLW       hi_addr(_txt+0)
	ADDWFC      _i+1, 0 
	MOVWF       FLOC__interrupt+1 
	CALL        _UART_Read+0, 0
	MOVFF       FLOC__interrupt+0, FSR1
	MOVFF       FLOC__interrupt+1, FSR1H
	MOVF        R0, 0 
	MOVWF       POSTINC1+0 
;GPS.c,28 :: 		i++;                           // Increment string index
	INFSNZ      _i+0, 1 
	INCF        _i+1, 1 
;GPS.c,29 :: 		if (i == 768) {                // If index = 768,
	MOVF        _i+1, 0 
	XORLW       3
	BTFSS       STATUS+0, 2 
	GOTO        L__interrupt9
	MOVLW       0
	XORWF       _i+0, 0 
L__interrupt9:
	BTFSS       STATUS+0, 2 
	GOTO        L_interrupt1
;GPS.c,30 :: 		i = 0;                       //   set it to zero
	CLRF        _i+0 
	CLRF        _i+1 
;GPS.c,31 :: 		ready = 1;                     // Ready for parsing GPS data
	MOVLW       1
	MOVWF       _ready+0 
;GPS.c,32 :: 		}
L_interrupt1:
;GPS.c,33 :: 		RCIF_bit = 0;                    // Set RCIF to 0 register for uart interrupt
	BCF         RCIF_bit+0, BitPos(RCIF_bit+0) 
;GPS.c,34 :: 		}
L_interrupt0:
;GPS.c,35 :: 		}
L_end_interrupt:
L__interrupt8:
	RETFIE      1
; end of _interrupt

_main:

;GPS.c,37 :: 		void main(){
;GPS.c,42 :: 		ADCON1=0X0F;
	MOVLW       15
	MOVWF       ADCON1+0 
;GPS.c,43 :: 		CMCON=7;
	MOVLW       7
	MOVWF       CMCON+0 
;GPS.c,44 :: 		Lcd_Init();                        // Initialize Lcd
	CALL        _Lcd_Init+0, 0
;GPS.c,46 :: 		Lcd_Cmd(_LCD_CLEAR);               // Clear display
	MOVLW       1
	MOVWF       FARG_Lcd_Cmd_out_char+0 
	CALL        _Lcd_Cmd+0, 0
;GPS.c,47 :: 		Lcd_Cmd(_LCD_CURSOR_OFF);          // Cursor off
	MOVLW       12
	MOVWF       FARG_Lcd_Cmd_out_char+0 
	CALL        _Lcd_Cmd+0, 0
;GPS.c,48 :: 		Lcd_out(1,1,"GPS Time:");
	MOVLW       1
	MOVWF       FARG_Lcd_Out_row+0 
	MOVLW       1
	MOVWF       FARG_Lcd_Out_column+0 
	MOVLW       ?lstr1_GPS+0
	MOVWF       FARG_Lcd_Out_text+0 
	MOVLW       hi_addr(?lstr1_GPS+0)
	MOVWF       FARG_Lcd_Out_text+1 
	CALL        _Lcd_Out+0, 0
;GPS.c,49 :: 		Lcd_out(2,1,"Waiting");
	MOVLW       2
	MOVWF       FARG_Lcd_Out_row+0 
	MOVLW       1
	MOVWF       FARG_Lcd_Out_column+0 
	MOVLW       ?lstr2_GPS+0
	MOVWF       FARG_Lcd_Out_text+0 
	MOVLW       hi_addr(?lstr2_GPS+0)
	MOVWF       FARG_Lcd_Out_text+1 
	CALL        _Lcd_Out+0, 0
;GPS.c,51 :: 		ready = 0;                       // Initialize variables
	CLRF        _ready+0 
;GPS.c,52 :: 		i = 0;
	CLRF        _i+0 
	CLRF        _i+1 
;GPS.c,54 :: 		UART1_Init(9600);                // Initialize UART module at 9600
	BSF         BAUDCON+0, 3, 0
	MOVLW       2
	MOVWF       SPBRGH+0 
	MOVLW       8
	MOVWF       SPBRG+0 
	BSF         TXSTA+0, 2, 0
	CALL        _UART1_Init+0, 0
;GPS.c,57 :: 		RCIE_bit = 1;                   // Enable USART Receiver interrupt
	BSF         RCIE_bit+0, BitPos(RCIE_bit+0) 
;GPS.c,58 :: 		GIE_bit = 1;                     // Enable Global interrupt
	BSF         GIE_bit+0, BitPos(GIE_bit+0) 
;GPS.c,59 :: 		PEIE_bit = 1;                    // Enable Peripheral interrupt
	BSF         PEIE_bit+0, BitPos(PEIE_bit+0) 
;GPS.c,61 :: 		while(1) {
L_main2:
;GPS.c,62 :: 		OERR_bit = 0;                 // Set OERR to 0  overrun error bit in uart
	BCF         OERR_bit+0, BitPos(OERR_bit+0) 
;GPS.c,63 :: 		FERR_bit = 0;                 // Set FERR to 0  framming error bit in uart
	BCF         FERR_bit+0, BitPos(FERR_bit+0) 
;GPS.c,65 :: 		if(ready == 1) {               // If the data in txt array is ready do:
	MOVF        _ready+0, 0 
	XORLW       1
	BTFSS       STATUS+0, 2 
	GOTO        L_main4
;GPS.c,66 :: 		ready = 0;
	CLRF        _ready+0 
;GPS.c,67 :: 		string = strstr(txt,"$GPGGA");   //locates the first position of $GPGLL in txt
	MOVLW       _txt+0
	MOVWF       FARG_strstr_s1+0 
	MOVLW       hi_addr(_txt+0)
	MOVWF       FARG_strstr_s1+1 
	MOVLW       ?lstr3_GPS+0
	MOVWF       FARG_strstr_s2+0 
	MOVLW       hi_addr(?lstr3_GPS+0)
	MOVWF       FARG_strstr_s2+1 
	CALL        _strstr+0, 0
	MOVF        R0, 0 
	MOVWF       _string+0 
	MOVF        R1, 0 
	MOVWF       _string+1 
;GPS.c,69 :: 		if(string != 0) {            // If txt array contains "$GPGLL" string we proceed...
	MOVLW       0
	XORWF       R1, 0 
	BTFSS       STATUS+0, 2 
	GOTO        L__main11
	MOVLW       0
	XORWF       R0, 0 
L__main11:
	BTFSC       STATUS+0, 2 
	GOTO        L_main5
;GPS.c,70 :: 		if(string[7] != ',') {     // If "$GPGLL" NMEA message have ',' sign in the 8-th
	MOVLW       7
	ADDWF       _string+0, 0 
	MOVWF       FSR0 
	MOVLW       0
	ADDWFC      _string+1, 0 
	MOVWF       FSR0H 
	MOVF        POSTINC0+0, 0 
	XORLW       44
	BTFSC       STATUS+0, 2 
	GOTO        L_main6
;GPS.c,75 :: 		Lcd_Cmd(_LCD_CLEAR);
	MOVLW       1
	MOVWF       FARG_Lcd_Cmd_out_char+0 
	CALL        _Lcd_Cmd+0, 0
;GPS.c,76 :: 		Lcd_Cmd(_LCD_CURSOR_OFF);
	MOVLW       12
	MOVWF       FARG_Lcd_Cmd_out_char+0 
	CALL        _Lcd_Cmd+0, 0
;GPS.c,78 :: 		Lcd_out(1,1,"time=");
	MOVLW       1
	MOVWF       FARG_Lcd_Out_row+0 
	MOVLW       1
	MOVWF       FARG_Lcd_Out_column+0 
	MOVLW       ?lstr4_GPS+0
	MOVWF       FARG_Lcd_Out_text+0 
	MOVLW       hi_addr(?lstr4_GPS+0)
	MOVWF       FARG_Lcd_Out_text+1 
	CALL        _Lcd_Out+0, 0
;GPS.c,79 :: 		Lcd_Chr_Cp(string[7]);
	MOVLW       7
	ADDWF       _string+0, 0 
	MOVWF       FSR0 
	MOVLW       0
	ADDWFC      _string+1, 0 
	MOVWF       FSR0H 
	MOVF        POSTINC0+0, 0 
	MOVWF       FARG_Lcd_Chr_CP_out_char+0 
	CALL        _Lcd_Chr_CP+0, 0
;GPS.c,80 :: 		Lcd_Chr_Cp(string[8]);
	MOVLW       8
	ADDWF       _string+0, 0 
	MOVWF       FSR0 
	MOVLW       0
	ADDWFC      _string+1, 0 
	MOVWF       FSR0H 
	MOVF        POSTINC0+0, 0 
	MOVWF       FARG_Lcd_Chr_CP_out_char+0 
	CALL        _Lcd_Chr_CP+0, 0
;GPS.c,81 :: 		Lcd_Chr_Cp(':');
	MOVLW       58
	MOVWF       FARG_Lcd_Chr_CP_out_char+0 
	CALL        _Lcd_Chr_CP+0, 0
;GPS.c,82 :: 		Lcd_Chr_Cp(string[9]);
	MOVLW       9
	ADDWF       _string+0, 0 
	MOVWF       FSR0 
	MOVLW       0
	ADDWFC      _string+1, 0 
	MOVWF       FSR0H 
	MOVF        POSTINC0+0, 0 
	MOVWF       FARG_Lcd_Chr_CP_out_char+0 
	CALL        _Lcd_Chr_CP+0, 0
;GPS.c,83 :: 		Lcd_Chr_Cp(string[10]);
	MOVLW       10
	ADDWF       _string+0, 0 
	MOVWF       FSR0 
	MOVLW       0
	ADDWFC      _string+1, 0 
	MOVWF       FSR0H 
	MOVF        POSTINC0+0, 0 
	MOVWF       FARG_Lcd_Chr_CP_out_char+0 
	CALL        _Lcd_Chr_CP+0, 0
;GPS.c,84 :: 		Lcd_out(2,1,"lat=");
	MOVLW       2
	MOVWF       FARG_Lcd_Out_row+0 
	MOVLW       1
	MOVWF       FARG_Lcd_Out_column+0 
	MOVLW       ?lstr5_GPS+0
	MOVWF       FARG_Lcd_Out_text+0 
	MOVLW       hi_addr(?lstr5_GPS+0)
	MOVWF       FARG_Lcd_Out_text+1 
	CALL        _Lcd_Out+0, 0
;GPS.c,85 :: 		Lcd_Chr_Cp(string[17]);
	MOVLW       17
	ADDWF       _string+0, 0 
	MOVWF       FSR0 
	MOVLW       0
	ADDWFC      _string+1, 0 
	MOVWF       FSR0H 
	MOVF        POSTINC0+0, 0 
	MOVWF       FARG_Lcd_Chr_CP_out_char+0 
	CALL        _Lcd_Chr_CP+0, 0
;GPS.c,86 :: 		Lcd_Chr_Cp(string[18]);
	MOVLW       18
	ADDWF       _string+0, 0 
	MOVWF       FSR0 
	MOVLW       0
	ADDWFC      _string+1, 0 
	MOVWF       FSR0H 
	MOVF        POSTINC0+0, 0 
	MOVWF       FARG_Lcd_Chr_CP_out_char+0 
	CALL        _Lcd_Chr_CP+0, 0
;GPS.c,87 :: 		Lcd_Chr_Cp(string[19]);
	MOVLW       19
	ADDWF       _string+0, 0 
	MOVWF       FSR0 
	MOVLW       0
	ADDWFC      _string+1, 0 
	MOVWF       FSR0H 
	MOVF        POSTINC0+0, 0 
	MOVWF       FARG_Lcd_Chr_CP_out_char+0 
	CALL        _Lcd_Chr_CP+0, 0
;GPS.c,88 :: 		Lcd_Chr_Cp(string[20]);
	MOVLW       20
	ADDWF       _string+0, 0 
	MOVWF       FSR0 
	MOVLW       0
	ADDWFC      _string+1, 0 
	MOVWF       FSR0H 
	MOVF        POSTINC0+0, 0 
	MOVWF       FARG_Lcd_Chr_CP_out_char+0 
	CALL        _Lcd_Chr_CP+0, 0
;GPS.c,89 :: 		Lcd_Chr_Cp(string[28]);
	MOVLW       28
	ADDWF       _string+0, 0 
	MOVWF       FSR0 
	MOVLW       0
	ADDWFC      _string+1, 0 
	MOVWF       FSR0H 
	MOVF        POSTINC0+0, 0 
	MOVWF       FARG_Lcd_Chr_CP_out_char+0 
	CALL        _Lcd_Chr_CP+0, 0
;GPS.c,92 :: 		Lcd_out(3,1,"long=");
	MOVLW       3
	MOVWF       FARG_Lcd_Out_row+0 
	MOVLW       1
	MOVWF       FARG_Lcd_Out_column+0 
	MOVLW       ?lstr6_GPS+0
	MOVWF       FARG_Lcd_Out_text+0 
	MOVLW       hi_addr(?lstr6_GPS+0)
	MOVWF       FARG_Lcd_Out_text+1 
	CALL        _Lcd_Out+0, 0
;GPS.c,93 :: 		Lcd_Chr_Cp(string[30]);
	MOVLW       30
	ADDWF       _string+0, 0 
	MOVWF       FSR0 
	MOVLW       0
	ADDWFC      _string+1, 0 
	MOVWF       FSR0H 
	MOVF        POSTINC0+0, 0 
	MOVWF       FARG_Lcd_Chr_CP_out_char+0 
	CALL        _Lcd_Chr_CP+0, 0
;GPS.c,94 :: 		Lcd_Chr_Cp(string[31]);
	MOVLW       31
	ADDWF       _string+0, 0 
	MOVWF       FSR0 
	MOVLW       0
	ADDWFC      _string+1, 0 
	MOVWF       FSR0H 
	MOVF        POSTINC0+0, 0 
	MOVWF       FARG_Lcd_Chr_CP_out_char+0 
	CALL        _Lcd_Chr_CP+0, 0
;GPS.c,95 :: 		Lcd_Chr_Cp(string[32]);
	MOVLW       32
	ADDWF       _string+0, 0 
	MOVWF       FSR0 
	MOVLW       0
	ADDWFC      _string+1, 0 
	MOVWF       FSR0H 
	MOVF        POSTINC0+0, 0 
	MOVWF       FARG_Lcd_Chr_CP_out_char+0 
	CALL        _Lcd_Chr_CP+0, 0
;GPS.c,96 :: 		Lcd_Chr_Cp(string[33]);
	MOVLW       33
	ADDWF       _string+0, 0 
	MOVWF       FSR0 
	MOVLW       0
	ADDWFC      _string+1, 0 
	MOVWF       FSR0H 
	MOVF        POSTINC0+0, 0 
	MOVWF       FARG_Lcd_Chr_CP_out_char+0 
	CALL        _Lcd_Chr_CP+0, 0
;GPS.c,97 :: 		Lcd_Chr_Cp(string[42]);
	MOVLW       42
	ADDWF       _string+0, 0 
	MOVWF       FSR0 
	MOVLW       0
	ADDWFC      _string+1, 0 
	MOVWF       FSR0H 
	MOVF        POSTINC0+0, 0 
	MOVWF       FARG_Lcd_Chr_CP_out_char+0 
	CALL        _Lcd_Chr_CP+0, 0
;GPS.c,102 :: 		}
L_main6:
;GPS.c,103 :: 		}
L_main5:
;GPS.c,104 :: 		}
L_main4:
;GPS.c,105 :: 		}
	GOTO        L_main2
;GPS.c,106 :: 		}
L_end_main:
	GOTO        $+0
; end of _main
